COMPONENT_SRCDIRS := .
COMPONENT_SRCDIRS += src/ILI9486

COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_ADD_INCLUDEDIRS += include/ILI9486/Fonts
COMPONENT_ADD_INCLUDEDIRS += include/ILI9486
COMPONENT_ADD_INCLUDEDIRS += include
